# Generated by Django 6.0.4 on 2026-04-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('items', models.TextField()),
                ('amount', models.IntegerField()),
                ('pickup_type', models.CharField(choices=[('Dine-in', 'Dine-in'), ('Takeaway', 'Takeaway')], default='Takeaway', max_length=20)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Card', 'Card')], default='Cash', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ready', 'Ready'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
