# Generated by Django 6.0.4 on 2026-04-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCanteen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash on Counter'), ('Bkash', 'bKash'), ('Nagad', 'Nagad'), ('Card', 'Card')], default='Cash', max_length=20),
        ),
    ]
