# Generated by Django 5.2.7 on 2026-05-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCanteen', '0006_specialitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialitem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='specialitem',
            name='emoji',
            field=models.CharField(default='🍽️', max_length=10),
        ),
    ]
