# Generated by Django 5.2.7 on 2026-05-08 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCanteen', '0007_remove_specialitem_created_at_specialitem_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
