# Generated by Django 5.2.7 on 2026-05-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCanteen', '0008_specialitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
