# Generated by Django 5.2.7 on 2026-05-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCanteen', '0009_food_available_food_category_food_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='emoji',
            field=models.CharField(default='🍽️', max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
