# Generated by Django 5.2.7 on 2026-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCanteen', '0010_food_emoji_alter_food_category_alter_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Takeaway', 'Takeaway'), ('Dine-in', 'Dine-in')], default='Takeaway', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], default='Cash', max_length=20),
        ),
    ]
