# Generated by Django 5.2.7 on 2026-05-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCanteen', '0012_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='specialitem',
            name='emoji',
        ),
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AddField(
            model_name='specialitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='special_items/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Bread', 'Bread'), ('Snacks', 'Snacks'), ('Drinks', 'Drinks'), ('Dessert', 'Dessert')], default='Snacks', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff')], default='Student', max_length=20),
        ),
    ]
