# Generated by Django 5.2.7 on 2026-05-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCanteen', '0013_remove_food_emoji_remove_specialitem_emoji_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialitem',
            old_name='photo',
            new_name='image',
        ),
    ]
