# Generated by Django 5.2.7 on 2026-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCanteen', '0015_order_user_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready', 'Ready'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
